env:
  node: true
  es6: true
extends: 'eslint:recommended'
rules:
  no-console: off
  no-unused-vars: off
  eqeqeq: warn
  semi:
    - error
    - always
  no-mixed-spaces-and-tabs:
    - error
    - smart-tabs
  indent:
    - error
    - tab
globals:
  FullCalendar: false
  moment: false
  hotkeys: false
